---

- hosts: hosts
  tasks:
    - name: set DNS Servers
      community.vmware.vmware_host_dns_info:
        hostname: osi-vcenter.optimaxsi.com
        username: root
        password: P@ssw0rd
        esxi_hostname: osi-esx01.optimaxsi.com
      delegate_to: localhost
